name: ip_locator_env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiosqlite=0.18.0
  - annotated-types=0.7.0
  - anyio=4.8.0
  - asyncpg=0.29.0
  - black=24.10.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - click=8.1.7
  - dnspython=2.7.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.2
  - expat=2.6.4
  - fastapi=0.115.7
  - fastapi-cli=0.0.7
  - flake8=7.1.1
  - freezegun=1.5.1
  - greenlet=3.1.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - iniconfig=1.1.1
  - jinja2=3.1.5
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libuv=1.50.0
  - loguru=0.7.2
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - openssl=3.4.0
  - packaging=24.2
  - pathspec=0.10.3
  - pip=24.2
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - pycodestyle=2.12.1
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pyflakes=3.2.0
  - pygments=2.19.1
  - pysocks=1.7.1
  - pytest=8.3.4
  - pytest-asyncio=0.25.3
  - python=3.12.8
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-multipart=0.0.20
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - rich-toolkit=0.11.3
  - setuptools=75.1.0
  - shellingham=1.5.4
  - six=1.16.0
  - sniffio=1.3.1
  - sqlalchemy=2.0.37
  - sqlite=3.45.3
  - starlette=0.45.2
  - tk=8.6.14
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - uvicorn=0.34.0
  - uvicorn-standard=0.34.0
  - uvloop=0.21.0
  - watchfiles=0.24.0
  - websockets=10.4
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
